### ISSUE TITLE
Chapter -2

### ISSUE THREAD

**Issue by vovs03** [vovs03/terraform-bookex#4]
# Chapter -2

- [x] `p.59-99`
  - [x] Прочитаны
  - [x] Проработаны
  - [x] Есть рабочий код
     - [x] web-server #5

## stages

- [x] 👍🏻 конфигурируемый вэб-сервер #6
- [x] развёрнутый кластер вэб-серверов #7
- [x] развёрнутый балансировщик нагрузки #8

**Comment by vovs03** [comment]
https://github.com/brikis98

**Comment by vovs03** [comment]
# Test example

- [x] ⚗️  test/go_sanity_test.go From `Chapter 7`
